# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ArchitecturalInsight": types.ArchitecturalInsight,
    "stream_types.ArchitecturalInsight": stream_types.ArchitecturalInsight,

    "types.CodeAnalysis": types.CodeAnalysis,
    "stream_types.CodeAnalysis": stream_types.CodeAnalysis,

    "types.CodeComponent": types.CodeComponent,
    "stream_types.CodeComponent": stream_types.CodeComponent,

    "types.Dependency": types.Dependency,
    "stream_types.Dependency": stream_types.Dependency,

    "types.OperationalInsight": types.OperationalInsight,
    "stream_types.OperationalInsight": stream_types.OperationalInsight,

    "types.PerformanceInsight": types.PerformanceInsight,
    "stream_types.PerformanceInsight": stream_types.PerformanceInsight,

    "types.SecurityAnalysis": types.SecurityAnalysis,
    "stream_types.SecurityAnalysis": stream_types.SecurityAnalysis,

    "types.TestingInsight": types.TestingInsight,
    "stream_types.TestingInsight": stream_types.TestingInsight,


    "types.ArchitecturalPattern": types.ArchitecturalPattern,

    "types.ComponentType": types.ComponentType,

    "types.QualityIssue": types.QualityIssue,

}