# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CodeAnalysis": types.CodeAnalysis,
    "stream_types.CodeAnalysis": stream_types.CodeAnalysis,

    "types.CodeComponent": types.CodeComponent,
    "stream_types.CodeComponent": stream_types.CodeComponent,

    "types.Dependency": types.Dependency,
    "stream_types.Dependency": stream_types.Dependency,


    "types.ComponentType": types.ComponentType,

}